Repository aq33/NSV13, pull requests merged in 2024-02, with the labels that each got.

#78 Dodaje małpi hełm, skiny borgów + jakąś tam krew
  aquila/aquila.dm
  aquila/code/game/objects/effects/decals/cleanable.dm
  aquila/code/game/objects/effects/decals/cleanable/humans.dm
  aquila/code/modules/cargo/packs.dm
  aquila/code/modules/clothing/head/mind_monkey_helmet.dm
  aquila/code/modules/mob/living/carbon/monkey/monkey.dm
  aquila/code/modules/mob/living/silicon/robot/robot_modules.dm
  aquila/icons/mob/head.dmi
  aquila/icons/obj/clothing/hats.dmi
  code/__DEFINES/misc.dm
  code/__DEFINES/role_preferences.dm
  code/__DEFINES/traits.dm
  code/_globalvars/lists/poll_ignore.dm
  code/_globalvars/traits.dm
  code/datums/brain_damage/severe.dm
  code/game/objects/effects/decals/cleanable.dm
  code/game/objects/effects/decals/cleanable/humans.dm
  code/game/objects/items/storage/storage.dm
  code/modules/antagonists/cult/blood_magic.dm
  code/modules/clothing/head/_head.dm
  code/modules/clothing/masks/_masks.dm
  code/modules/clothing/under/_under.dm
  code/modules/guardian/abilities/major/predator.dm
  code/modules/mob/living/blood.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/mob/living/simple_animal/bot/cleanbot.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/bubblegum.dm
  code/modules/research/xenobiology/crossbreeding/_structures.dm
  code/modules/tgui/status_composers.dm
  icons/mob/robots.dmi
  nsv13/code/game/objects/items/bloody_eye.dm
  tools/Runtime Condenser/Output.txt
Labels: sprites, tools

#75 Borgi [Port 402]
  aquila/aquila.dm
  aquila/code/game/objects/items/robot/robot_upgrades.dm
  aquila/code/modules/research/designs/mechfabricator_designs.dm
  aquila/code/modules/research/techweb/all_nodes.dm
Labels: Feature

#80 borgi do wyboru do koloru
  code/modules/mob/living/silicon/robot/robot.dm
Labels: Feature

#60 joker rozdaje drain bamage
  aquila/aquila.dm
  aquila/code/controllers/configuration/entries/game_options.dm
  aquila/code/controllers/configuration/entries/general.dm
  code/__DEFINES/say.dm
  code/controllers/configuration/configuration.dm
  code/modules/mob/living/say.dm
  config/config.txt
  config/ranks/corporate.txt
  config/ranks/military.txt
  config/ranks/royal_navy.txt
  config/ranks/sharpe.txt
  config/roleplay_filter.txt
Labels: Feature

#79 zmiany z dotychczasowych gier
  code/controllers/subsystem/events.dm
  code/modules/events/anomaly_flux.dm
  code/modules/events/beer_clog.dm
  code/modules/events/brain_trauma.dm
  code/modules/events/fugitive_spawning.dm
  config/admins.txt
  config/game_options.txt
  config/jobs.txt
  config/maps.txt
  nsv13.dme
  nsv13/sound/weapons/glock.ogg
  nsv13/sound/weapons/rifle_fire.ogg
  nsv13/sound/weapons/smg_fire.ogg
  sound/ambience/title5.ogg
  sound/ambience/title6.ogg
  sound/roundend/adios.ogg
  sound/roundend/cipki.ogg
  sound/roundend/dzokerowski_smiec.ogg
  sound/roundend/nara.ogg
  strings/round_start_sounds.txt
Labels: Dźwięk, Tweak, Config Update, sound

#81 Map fixes 4
  _maps/map_files/Atlas/atlas.dmm
  _maps/map_files/Atlas/atlas2.dmm
  _maps/map_files/Mining/nsv13/gulag.dmm
  _maps/map_files/Serendipity/Serendipity1.dmm
Labels: mapping

#82 hotfix do atlantis plus atlas
  _maps/map_files/Atlantis/Atlantis2.dmm
  _maps/map_files/Atlas/atlas.dmm
Labels: mapping

#73 Pakiet tłumaczeń
  code/__DEFINES/jobs.dm
  code/datums/ai/dog/dog_controller.dm
  code/datums/components/aiming.dm
  code/datums/diseases/advance/symptoms/shivering.dm
  code/datums/weather/weather_types/radiation_storm.dm
  code/game/area/Space_Station_13_areas.dm
  code/game/machinery/announcement_system.dm
  code/game/machinery/doppler_array.dm
  code/game/objects/items/religion.dm
  code/modules/cargo/orderconsole.dm
  code/modules/clothing/masks/hailer.dm
  code/modules/economy/account.dm
  code/modules/events/ion_storm.dm
  code/modules/events/shuttle_loan.dm
  code/modules/mob/living/simple_animal/friendly/dog.dm
  code/modules/research/machinery/_production.dm
  code/modules/shuttle/emergency.dm
  code/modules/vending/_vending.dm
  nsv13/code/controllers/subsystem/overmap_mode.dm
  nsv13/code/controllers/subsystem/ranks.dm
  nsv13/code/game/gamemodes/overmap/courier.dm
  nsv13/code/game/gamemodes/overmap/shakedown.dm
  nsv13/code/modules/antagonists/simple_teamchat.dm
  nsv13/code/modules/clothing/masks/hailer.dm
  nsv13/code/modules/mob/living/carbon/human/species_types/catgirl.dm
  nsv13/code/modules/mob/living/carbon/human/species_types/other_knpc.dm
  nsv13/code/modules/mob/living/carbon/human/species_types/spacepirate_knpc.dm
  nsv13/code/modules/mob/living/carbon/human/species_types/syndicate_knpc.dm
  nsv13/code/modules/overmap/FTL/ftl_jump.dm
  nsv13/code/modules/overmap/FTL/ftl_legacy.dm
  nsv13/code/modules/overmap/ai-skynet.dm
  nsv13/code/modules/overmap/factions.dm
  nsv13/code/modules/overmap/fleet_combat/combat_handling.dm
  nsv13/code/modules/overmap/overmap.dm
  nsv13/code/modules/overmap/weapons/damage.dm
  nsv13/code/modules/research/astrometrics.dm
  strings/ion_laws.json
Labels: Tłumaczenie

#86 Reload Whitelist Verb
  code/modules/admin/admin.dm
  code/modules/admin/admin_verbs.dm
Labels: Administration

#88 poprawki dla jokera
  _maps/map_files/Atlas/atlas.dmm
  _maps/map_files/Atlas/atlas2.dmm
Labels: mapping

#89 jokerze
  _maps/map_files/Atlas/atlas.dmm
  _maps/map_files/Atlas/atlas2.dmm
  _maps/shuttles/emergency/emergency_raven.dmm
Labels: Mapa

#92 Autodoc
  aquila/code/game/objects/items/circuitboards/machine_circuitboards.dm
  aquila/code/modules/research/designs/machine_designs.dm
  aquila/code/modules/research/techweb/all_nodes.dm
Labels: Feature

#93 zmiany dotyczące hajsu oraz kodów nuklearnych
  aquila/aquila.dm
  aquila/code/controllers/configuration/entries/game_options.dm
  aquila/code/modules/metacoin/metacoin.dm
  aquila/code/modules/requests/request.dm
  code/__HELPERS/roundend.dm
  code/game/objects/items/cards_ids.dm
  code/modules/requests/request.dm
  config/game_options.txt
Labels: Feature

#94 Podmiana Ikon broni NSV
  code/modules/projectiles/boxes_magazines/external/rifle.dm
  icons/obj/ammo.dmi
  nsv13/code/game/objects/items/custom_guns.dm
  nsv13/code/modules/jobs/security/weapons.dm
  nsv13/icons/mob/inhands/weapons/guns_lefthand.dmi
  nsv13/icons/mob/inhands/weapons/guns_righthand.dmi
  nsv13/icons/obj/ammo.dmi
  nsv13/icons/obj/guns/guns_big.dmi
  nsv13/icons/obj/guns/projectile.dmi
Labels: Sprite

#87 dżokerowskie balansy
  nsv13/code/modules/jobs/security/weapons.dm
Labels: Tweak

#98 spowolnienie lasera
  code/modules/projectiles/guns/energy/laser.dm
Labels: Tweak

#103 poprawki do atlantis
  _maps/map_files/Atlantis/Atlantis.dmm
  _maps/map_files/Atlantis/Atlantis2.dmm
Labels: mapping

#107 zmienia domyślne bezużyteczne BSA na BSA jako broń statku
  code/modules/station_goals/bsa.dm
Labels: Tweak

#165 jajoskręt
  aquila/aquila.dm
  aquila/code/modules/surgery/gender_reassignment.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human_defines.dm
Labels: Feature

#166 [atlas] dodaje dropship
  _maps/map_files/Atlas/atlas.dmm
  _maps/map_files/Atlas/atlas2.dmm
  _maps/shuttles/cargo/cargo_atlas.dmm
Labels: mapping

#168 sufit
  _maps/map_files/Atlas/atlas.dmm
  _maps/map_files/Atlas/atlas2.dmm
Labels: Mapa, Bug Fix

#105 Dżokerowskie tłiki
  aquila/aquila.dm
  aquila/code/game/objects/effects/spawners/lootdrop.dm
  aquila/code/game/objects/effects/spawners/xenospawner.dm
  aquila/code/modules/antagonists/morph/morph.dm
  aquila/code/modules/client/verbs/input_box.dm
  aquila/code/modules/mob/living/simple_animal/simple_animal.dm
  aquila/code/modules/mob/typing_indicator.dm
  aquila/code/modules/research/designs/biogenerator_designs.dm
  aquila/code/modules/research/techweb/all_nodes.dm
  code/__DEFINES/mobs.dm
  code/controllers/subsystem/input.dm
  code/modules/client/verbs/input_box.dm
Labels: Feature, Tweak

#174 Dodaje ghost role do gulagu i guzik na ghost role
  _maps/RandomRuins/GulagRuins/ashwalker.dmm
  _maps/RandomRuins/GulagRuins/gameroom.dmm
  _maps/RandomRuins/GulagRuins/golem.dmm
  _maps/RandomRuins/GulagRuins/menele.dmm
  _maps/RandomRuins/GulagRuins/seed.dmm
  _maps/RandomRuins/GulagRuins/syndicate_bio.dmm
  _maps/RandomRuins/GulagRuins/syndicate_listening.dmm
  _maps/map_files/Mining/nsv13/gulag.dmm
  code/_onclick/hud/_defines.dm
  code/_onclick/hud/ghost.dm
  code/_onclick/hud/screen_objects.dm
  code/game/objects/effects/spawners/roomspawner.dm
  code/game/objects/structures/ghost_role_spawners.dm
  code/modules/jobs/jobs.dm
  code/modules/mapping/random_rooms.dm
  icons/mob/screen_ghost.dmi
  icons/mob/screen_midnight.dmi
Labels: Feature, Mapa

#175 przywraca brakujący przycisk heretykom
  code/modules/antagonists/heretic/heretic_antag.dm
Labels: Bug Fix

#192 bateria eksportowa
  aquila/aquila.dm
  aquila/code/game/machinery/battery.dm
  aquila/code/game/objects/items/circuitboards/machine_circuitboards.dm
  aquila/code/modules/cargo/exports/large_objects.dm
  aquila/code/modules/research/designs/power_designs.dm
  aquila/icons/obj/machines/battery_export.dmi
  code/modules/cargo/exports.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Port, Feature

#195 szczury
  aquila/aquila.dm
  aquila/code/__DEFINES/movespeed_modification.dm
  aquila/code/modules/language/mouse.dm
  aquila/code/modules/mob/dead/observer/observer.dm
  aquila/code/modules/mob/living/simple_animal/friendly/mouse.dm
  code/__HELPERS/roundend.dm
  code/modules/assembly/mousetrap.dm
  code/modules/language/language_holder.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/simple_animal/friendly/mouse.dm
Labels: Port, Feature

#196 Gaz BZ i tweaki
  aquila/aquila.dm
  aquila/code/modules/cargo/packs.dm
  aquila/code/modules/reagents/chemistry/reagents/other_reagents.dm
  aquila/code/modules/reagents/chemistry/recipes/other_reagents.dm
  aquila/code/modules/reagents/reagent_containers/bottle.dm
  aquila/code/modules/research/designs/mecha_designs.dm
  code/game/machinery/computer/prisoner/gulag_teleporter.dm
  code/modules/cargo/packs.dm
  code/modules/mob/living/simple_animal/hostile/alien.dm
Labels: Port, Feature, Tweak

#197 polish
  _maps/map_files/Mining/nsv13/ruins/mining28.dmm
  code/__DEFINES/DNA.dm
  code/datums/mutations/speech.dm
  code/game/objects/items/dna_injector.dm
Labels: Tłumaczenie

#199 Port dymków 'Pointing at something on yourself now shows the item' #8553
  aquila/aquila.dm
  aquila/code/__DEFINES/hud.dm
  aquila/code/game/atoms.dm
  aquila/code/modules/point/point.dm
  aquila/icons/effects/effects.dmi
  code/game/objects/effects/decals/misc.dm
  code/game/objects/items.dm
  code/modules/mob/mob.dm
Labels: Port, Feature

#198 Tłumaczenie Bloba oraz resprite
  code/modules/antagonists/blob/blob.dm
  code/modules/antagonists/blob/blob_mobs.dm
  code/modules/antagonists/blob/blobstrains/_blobstrain.dm
  code/modules/antagonists/blob/blobstrains/blazing_oil.dm
  code/modules/antagonists/blob/blobstrains/cryogenic_poison.dm
  code/modules/antagonists/blob/blobstrains/electromagnetic_web.dm
  code/modules/antagonists/blob/blobstrains/energized_jelly.dm
  code/modules/antagonists/blob/blobstrains/explosive_lattice.dm
  code/modules/antagonists/blob/blobstrains/networked_fibers.dm
  code/modules/antagonists/blob/blobstrains/pressurized_slime.dm
  code/modules/antagonists/blob/blobstrains/reactive_spines.dm
  code/modules/antagonists/blob/blobstrains/regenerative_materia.dm
  code/modules/antagonists/blob/blobstrains/replicating_foam.dm
  code/modules/antagonists/blob/blobstrains/shifting_fragments.dm
  code/modules/antagonists/blob/blobstrains/synchronous_mesh.dm
  code/modules/antagonists/blob/blobstrains/zombifying_pods.dm
  code/modules/antagonists/blob/overmind.dm
  code/modules/antagonists/blob/powers.dm
  code/modules/antagonists/blob/structures/_blob.dm
  code/modules/antagonists/blob/structures/core.dm
  code/modules/antagonists/blob/structures/factory.dm
  code/modules/antagonists/blob/structures/node.dm
  code/modules/antagonists/blob/structures/resource.dm
  code/modules/antagonists/blob/structures/shield.dm
  html/antagtips/blob.html
  html/img/blobcore.png
  html/img/blobnode.png
  icons/mob/blob.dmi
Labels: Sprite, Tłumaczenie

#200 bateria hotfix
  aquila/code/modules/research/designs/power_designs.dm
Labels: Bug Fix

#201 [atlas] poprawki mapowe z wczoraj
  _maps/map_files/Atlas/atlas2.dmm
Labels: Mapa, Bug Fix

#203 ścisza PA
  code/modules/power/singularity/particle_accelerator/particle_control.dm
Labels: Dźwięk, Tweak

#204 Command w puli rol losowych
  code/controllers/subsystem/job.dm
Labels: Tweak

#205 Replay
  aquila/aquila.dm
  aquila/code/controllers/subsystem/demo.dm
  code/__DEFINES/subsystems.dm
  code/__HELPERS/mobs.dm
  code/_compile_options.dm
  code/_globalvars/logging.dm
  code/_onclick/hud/credits.dm
  code/controllers/subsystem/chat.dm
  code/controllers/subsystem/title.dm
  code/controllers/subsystem/zclear.dm
  code/game/machinery/telecomms/broadcasting.dm
  code/game/objects/effects/wanted_poster.dm
  code/game/world.dm
  code/modules/admin/verbs/deadsay.dm
  code/modules/client/verbs/looc.dm
  code/modules/client/verbs/ooc.dm
  code/modules/clothing/clothing.dm
  code/modules/mob/login.dm
  code/modules/modular_computers/file_system/programs/ntmessenger.dm
  code/modules/modular_computers/file_system/programs/ntnrc_client.dm
  code/modules/tgchat/to_chat.dm
  config/config.txt
  config/starmap/starmap.json
  demo-writer.dll
  libdemo-writer.so
  tools/deploy.sh
Labels: Port, Feature

#202 ser
  cheese.dmi
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/structures/crates_lockers/closets/secure/freezer.dm
  code/game/objects/structures/statues.dm
  code/modules/cargo/bounties/chef.dm
  code/modules/cargo/packs.dm
  code/modules/food_and_drinks/food/condiment.dm
  code/modules/food_and_drinks/food/customizables.dm
  code/modules/food_and_drinks/food/snacks_cheese.dm
  code/modules/food_and_drinks/food/snacks_meat.dm
  code/modules/food_and_drinks/food/snacks_other.dm
  code/modules/food_and_drinks/recipes/food_mixtures.dm
  code/modules/food_and_drinks/recipes/processor_recipes.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_misc.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species_types/golems.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/ruins/lavaland_ruin_code.dm
  food.dmi
  icons/mob/animal.dmi
  icons/obj/food/cheese.dmi
  icons/obj/stack_objects.dmi
  icons/obj/statue.dmi
  nsv13.dme
  stack_objects.dmi
  statue.dmi
Labels: Port, Feature, sprites

#214 [Atlas] Dodanie Turbiny do atmosa
  _maps/map_files/Atlas/atlas.dmm
  _maps/map_files/Atlas/atlas2.dmm
Labels: Mapa

#216 Tweak illegal tech
  aquila/code/modules/research/techweb/all_nodes.dm
Labels: Tweak

#218 riplay
  data/replays/__tu pojawia sie replaye__.txt
Labels: Bug Fix

#221 Beryl bardziej robustny
  strings/tips.txt
Labels: Tweak

#237 Aktualizacja medbaya - Unibel
  _maps/map_files/Atlas/atlas2.dmm
  _maps/map_files/Atlas/job_changes.dm
Labels: mapping

#223 animacje plecaków i takich
  code/datums/components/storage/concrete/_concrete.dm
  code/datums/components/storage/storage.dm
  code/game/objects/items/storage/bags.dm
Labels: Tweak

#224 Plort Machine
  aquila/aquila.dm
  aquila/code/game/objects/items/circuitboards/machine_circuitboards.dm
  aquila/code/modules/research/designs/machine_designs.dm
  aquila/code/modules/research/machinery/plortmachine.dm
  aquila/icons/obj/machines/plortmachine.dmi
  code/modules/research/xenobiology/xenobiology.dm
Labels: Port, Feature

#226 xray + mindread
  aquila/aquila.dm
  aquila/code/__DEFINES/DNA.dm
  aquila/code/datums/mutations/_combined.dm
  aquila/code/datums/mutations/antenna.dm
  aquila/code/game/objects/items/dna_injector.dm
Labels: Feature

#225 Viro Romerol
  code/datums/diseases/advance/symptoms/flesh_eating.dm
Labels: Feature

#228 Exolocomotive Xenomitosis
  aquila/aquila.dm
  aquila/code/datums/diseases/advance/symptoms/fleshgrowth.dm
  aquila/code/modules/mob/living/simple_animal/hostile/macrophage.dm
  aquila/icons/mob/animal.dmi
  aquila/icons/obj/smooth_structures/alien/flesh1.dmi
  aquila/icons/obj/smooth_structures/alien/flesh2.dmi
  aquila/icons/obj/smooth_structures/alien/flesh3.dmi
  aquila/icons/obj/smooth_structures/alien/fleshpolyp.dmi
  code/datums/diseases/advance/symptoms/macrophage.dm
  code/game/objects/structures/aliens.dm
Labels: Feature, Gotowe do merga

#229 Dodano nowy zestaw praw dla AI - Benjamin Netanyahu
  aquila/code/datums/ai_laws.dm
  aquila/code/game/objects/items/AI_modules.dm
  code/game/objects/effects/spawners/lootdrop.dm
  config/game_options.txt
Labels: Tweak

#231 Energy Harvester
  aquila/aquila.dm
  aquila/code/game/objects/structures/crate_lockers/closets/secure/engineering.dm
  aquila/code/modules/power/energyharvester.dm
Labels: Port, Feature

#232 Nowe random mainty z Bee
  _maps/RandomRooms/10x10/sk_rdm167_library_ritual.dmm
  _maps/RandomRooms/10x5/sk_rdm161_kilovault.dmm
  _maps/RandomRooms/3x3/sk_rdm162_control_room.dmm
  _maps/RandomRooms/3x3/sk_rdm163_corgi_butcher.dmm
  _maps/RandomRooms/3x3/sk_rdm164_cornucopia.dmm
  _maps/RandomRooms/3x3/sk_rdm_165_library.dmm
  _maps/RandomRooms/3x5/sk_rdm168_offish.dmm
  _maps/RandomRooms/5x4/sk_rdm166_printing_press.dmm
  _maps/RandomRooms/5x4/sk_rdm169_solars.dmm
  code/modules/mapping/random_rooms.dm
Labels: Mapa, mapping, Gotowe do merga

#227 Sentient Disease
  aquila/aquila.dm
  aquila/code/modules/antagonists/disease/disease_abilities.dm
  aquila/code/modules/antagonists/disease/disease_datum.dm
  aquila/code/modules/antagonists/disease/disease_disease.dm
  aquila/code/modules/antagonists/disease/disease_event.dm
  aquila/code/modules/antagonists/disease/disease_mob.dm
  code/datums/diseases/advance/advance.dm
Labels: Feature

#233 Łączenie Stasis Beds
  code/game/machinery/computer/Operating.dm
  code/game/machinery/stasis.dm
Labels: Port, Feature

#234 Richer Juice Trait
  code/modules/hydroponics/grown/citrus.dm
  code/modules/hydroponics/plant_genes.dm
  code/modules/hydroponics/seeds.dm
Labels: Port, Feature

#235 Machanie przedmiotami i jakieś inne bajery
  code/__DEFINES/obj_flags.dm
  code/_globalvars/bitfields.dm
  code/game/atoms_movable.dm
  code/game/objects/items.dm
  code/game/objects/items/devices/powersink.dm
  code/game/objects/items/toys.dm
  code/game/objects/structures/flora.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/carbon/carbon.dm
Labels: Port, Tweak

#238 Space Dragon Rework
  code/__DEFINES/movespeed_modification.dm
  code/controllers/subsystem/processing/gravity_aura.dm
  code/datums/action.dm
  code/datums/components/gravity_aura.dm
  code/datums/martial/tribal_claw.dm
  code/datums/saymode.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  code/modules/antagonists/space_dragon/carp_rift.dm
  code/modules/antagonists/space_dragon/space_dragon.dm
  code/modules/events/space_dragon.dm
  code/modules/mob/living/simple_animal/hostile/carp.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/drake.dm
  code/modules/mob/living/simple_animal/hostile/space_dragon.dm
  icons/mob/actions/actions_space_dragon.dmi
  icons/mob/spacedragon.dmi
  icons/obj/carp_rift.dmi
  nsv13.dme
  sound/creatures/space_dragon_roar.ogg
Labels: Port, Feature

#239 RTG do kupna
  aquila/code/modules/cargo/packs.dm
  code/modules/power/rtg.dm
Labels: Port, Feature

#243 Gastroctomy
  code/modules/research/designs/medical_designs.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/surgery/gastrectomy.dm
  code/modules/surgery/organs/stomach.dm
  icons/obj/surgery.dmi
Labels: Port, Feature

#244 Cortex folding
  code/__DEFINES/mobs.dm
  code/__DEFINES/traits.dm
  code/modules/mob/living/brain/brain_item.dm
  code/modules/research/designs/medical_designs.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/surgery/advanced/bioware/bioware.dm
  code/modules/surgery/advanced/bioware/cortex_folding.dm
  code/modules/surgery/advanced/bioware/cortex_imprint.dm
  code/modules/surgery/advanced/lobotomy.dm
  nsv13.dme
Labels: Port, Feature

#246 Ethereal krzyczy
  aquila/sound/voice/ethereal/ethereal_scream_1.ogg
  aquila/sound/voice/ethereal/ethereal_scream_2.ogg
  aquila/sound/voice/ethereal/ethereal_scream_3.ogg
  code/modules/mob/living/carbon/human/emote.dm
Labels: Dźwięk

#252 Egzorcysta za niecałe trzysta
  aquila/aquila.dm
  aquila/code/game/objects/items/holy_weapons.dm
  aquila/code/modules/projectiles/boxes_magazines/internal/shotgun.dm
  aquila/icons/mob/neck.dmi
  aquila/icons/obj/clothing/neck.dmi
  code/game/objects/items/holy_weapons.dm
Labels: Feature

#250 gatunki
  aquila/aquila.dm
  aquila/code/modules/mob/living/carbon/human/species_types/corporate.dm
  aquila/code/modules/mob/living/carbon/human/species_types/mushpeople.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Port, Feature

#247 Diabeł może płakać
  aquila/aquila.dm
  aquila/code/__DEFINES/antagonists.dm
  aquila/code/__DEFINES/is_helpers.dm
  aquila/code/__DEFINES/role_preferences.dm
  aquila/code/__DEFINES/traits.dm
  aquila/code/datums/mind.dm
  aquila/code/modules/antagonists/demon/demons.dm
  aquila/code/modules/antagonists/demon/general_powers.dm
  aquila/code/modules/antagonists/demon/objectives.dm
  aquila/code/modules/antagonists/demon/sins/envy.dm
  aquila/code/modules/antagonists/demon/sins/gluttony.dm
  aquila/code/modules/antagonists/demon/sins/greed.dm
  aquila/code/modules/antagonists/demon/sins/pride.dm
  aquila/code/modules/antagonists/demon/sins/wrath.dm
  aquila/code/modules/events/sinfuldemon.dm
  aquila/code/modules/mob/living/carbon/human/species.dm
  aquila/code/modules/reagents/chemistry/reagents/other_reagents.dm
  aquila/code/modules/ruins/objects_and_mobs/sin_ruins.dm
  aquila/code/modules/spells/spell_types/inflict_handler.dm
  aquila/icons/effects/mouse_pointers/throw_target.dmi
  aquila/icons/mob/actions/actions_minor_antag.dmi
  aquila/icons/mob/actions/humble/actions_humble.dmi
  aquila/icons/mob/hud.dmi
  aquila/icons/mob/mob.dmi
Labels: Port, Feature

#251 zmiany dot. floorpills
  code/modules/reagents/reagent_containers/pill.dm
Labels: Tweak

#253 Implementacja spriteów z Aquilla oraz Discord
  aquila/code/game/objects/effects/contraband.dm
  aquila/code/modules/food_and_drinks/drinks/drinks.dm
  aquila/code/modules/vending/boozeomat.dm
  aquila/icons/obj/contraband.dmi
  aquila/icons/obj/drinks.dmi
  code/modules/reagents/chemistry/machinery/pandemic.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
  code/modules/vending/cola.dm
  icons/mob/mask.dmi
  icons/obj/chemical.dmi
  icons/obj/drinks.dmi
  nsv13/icons/obj/card.dmi
Labels: Feature, Tweak
