Repository aq33/NSV13, pull requests merged in 2024-03, with the labels that each got.

#271 łorops rikłajed
  aquila/aquila.dm
  aquila/code/__HELPERS/pronouns.dm
  code/modules/antagonists/nukeop/equipment/nuclear_challenge.dm
  code/modules/shuttle/syndicate.dm
Labels: Tweak

#290 Naprawia spawny paru prac
  code/__DEFINES/jobs.dm
  code/game/objects/effects/landmarks.dm
Labels: Bug Fix

#289 quickfix picia dla ipc, ethereal i zombie
  code/modules/mob/living/carbon/human/species_types/IPC.dm
  code/modules/mob/living/carbon/human/species_types/ethereal.dm
  code/modules/mob/living/carbon/human/species_types/zombies.dm
Labels: Bug Fix

#286 ERT na zawołanie załogi - mniej więcej
  aquila/aquila.dm
  aquila/code/game/machinery/computer/communications.dm
  aquila/code/modules/requests/request.dm
  code/game/machinery/computer/communications.dm
  code/modules/admin/verbs/pray.dm
  code/modules/requests/request.dm
  code/modules/requests/request_manager.dm
  tgui/packages/tgui/interfaces/CommunicationsConsole.js
Labels: Feature

#288 [atlas] poprawki mapowe
  _maps/map_files/Atlas/atlas.dmm
  _maps/map_files/Atlas/atlas2.dmm
Labels: Mapa, Bug Fix, mapping

#287 Requested feature
  aquila/aquila.dm
  aquila/code/_onclick/hud/alert.dm
  aquila/code/controllers/configuration/entries/game_options.dm
  aquila/code/controllers/subsystem/vote.dm
  aquila/code/datums/weather/shitstorm.dm
  aquila/code/game/objects/effects/decals/cleanable/feces.dm
  aquila/code/game/objects/structures/watercloset.dm
  aquila/code/modules/events/shit_storm.dm
  aquila/code/modules/mob/living/carbon/human/human.dm
  aquila/code/modules/mob/living/carbon/human/species.dm
  aquila/code/modules/mob/living/living.dm
  aquila/code/modules/mob/living/living_defines.dm
  aquila/icons/effects/feces.dmi
  aquila/sound/creatures/fart.ogg
  aquila/sound/misc/toilet_flush.ogg
  code/__DEFINES/misc.dm
  code/__DEFINES/mobs.dm
  code/__DEFINES/traits.dm
  code/datums/components/mood.dm
  code/game/objects/effects/decals/cleanable.dm
  code/game/objects/effects/decals/cleanable/humans.dm
  code/modules/antagonists/cult/runes.dm
  code/modules/clothing/shoes/_shoes.dm
  code/modules/mob/living/carbon/human/physiology.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/android.dm
  code/modules/mob/living/carbon/human/species_types/ethereal.dm
  code/modules/mob/living/carbon/human/species_types/plasmamen.dm
  code/modules/mob/living/carbon/human/species_types/supersoldier.dm
  config/game_options.txt
  icons/effects/footprints.dmi
Labels: Feature, sprites, Config Update

#291 interns maj belowed
  aquila/code/modules/requests/request.dm
  tgui/packages/tgui/interfaces/CommunicationsConsole.js
Labels: TGUI-Changes

#293 [atlas] dodaje toalety
  _maps/map_files/Atlas/atlas.dmm
  _maps/map_files/Atlas/atlas2.dmm
Labels: mapping

#284 Vampires
  aquila/aquila.dm
  aquila/code/__DEFINES/_onclick/huds/vampire.dm
  aquila/code/__DEFINES/atom_hud.dm
  aquila/code/__DEFINES/role_preferences.dm
  aquila/code/datums/mind.dm
  aquila/code/game/gamemodes/vampire/grave_fever.dm
  aquila/code/game/gamemodes/vampire/traitor_vamp.dm
  aquila/code/game/gamemodes/vampire/vampire.dm
  aquila/code/game/gamemodes/vampire/vampire_bat.dm
  aquila/code/game/gamemodes/vampire/vampire_bite.dm
  aquila/code/game/gamemodes/vampire/vampire_hud.dm
  aquila/code/game/gamemodes/vampire/vampire_objective.dm
  aquila/code/game/gamemodes/vampire/vampire_other.dm
  aquila/code/game/gamemodes/vampire/vampire_powers.dm
  aquila/code/modules/admin/verbs/one_click_antag.dm
  aquila/code/modules/antagonists/vampire/vampire.dm
  aquila/code/modules/mob/living/carbon/carbon.dm
  aquila/code/modules/mob/living/carbon/human/human_defense.dm
  aquila/icons/mob/vampire.dmi
  aquila/sound/ambience/antag/lilithspact.ogg
  aquila/sound/ambience/antag/lilithspact_alt.ogg
  aquila/sound/ambience/antag/newvampire.ogg
  aquila/sound/ambience/antag/newvampire_alt.ogg
  aquila/sound/ambience/antag/vampire.ogg
  code/__byond_version_compat.dm
  code/datums/hud.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  config/game_options.txt
Labels: Port, Feature, Nagroda, Config Update

#261 Tlumaczenia
  code/datums/ai/dog/dog_controller.dm
  code/modules/mob/living/carbon/emote.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/simple_animal/parrot.dm
Labels: Tłumaczenie

#296 Infiltratorzy
  _maps/map_files/Atlas/atlas2.dmm
  _maps/map_files/generic/CentCom.dmm
  _maps/shuttles/infiltrator/infiltrator_cutter.dmm
  aquila/aquila.dm
  aquila/code/__DEFINES/antagonists.dm
  aquila/code/__DEFINES/atom_hud.dm
  aquila/code/__DEFINES/is_helpers.dm
  aquila/code/__DEFINES/misc.dm
  aquila/code/__DEFINES/role_preferences.dm
  aquila/code/__DEFINES/span.dm
  aquila/code/__DEFINES/uplink.dm
  aquila/code/__HELPERS/game.dm
  aquila/code/__HELPERS/unsorted.dm
  aquila/code/_globalvars/lists/game.dm
  aquila/code/datums/action.dm
  aquila/code/datums/components/uplink.dm
  aquila/code/datums/hud.dm
  aquila/code/datums/shuttles.dm
  aquila/code/game/area/areas/centcom.dm
  aquila/code/game/area/areas/shuttles.dm
  aquila/code/game/gamemodes/infiltration/infiltration.dm
  aquila/code/game/gamemodes/objective.dm
  aquila/code/game/gamemodes/objective_items.dm
  aquila/code/game/machinery/suit_storage_unit.dm
  aquila/code/game/objects/effects/landmarks.dm
  aquila/code/game/objects/items/devices/powersink.dm
  aquila/code/game/objects/items/implants/implant_dusting.dm
  aquila/code/game/objects/items/implants/implant_infiltrator.dm
  aquila/code/modules/admin/topic.dm
  aquila/code/modules/admin/verbs/one_click_antag.dm
  aquila/code/modules/antagonists/hijacked_ai/hijacked_ai.dm
  aquila/code/modules/antagonists/infiltrator/infiltrator.dm
  aquila/code/modules/antagonists/infiltrator/items/ai_hijack.dm
  aquila/code/modules/antagonists/infiltrator/items/hardsuit.dm
  aquila/code/modules/antagonists/infiltrator/items/services.dm
  aquila/code/modules/antagonists/infiltrator/objectives.dm
  aquila/code/modules/antagonists/infiltrator/outfit.dm
  aquila/code/modules/antagonists/infiltrator/team.dm
  aquila/code/modules/antagonists/role_preference/role_infiltrator.dm
  aquila/code/modules/antagonists/role_preference/role_sinfuldemon.dm
  aquila/code/modules/antagonists/traitor/equipment/Malf_Modules.dm
  aquila/code/modules/events/infiltrators.dm
  aquila/code/modules/mob/living/silicon/ai/ai.dm
  aquila/code/modules/mob/living/silicon/ai/death.dm
  aquila/code/modules/mob/living/silicon/ai/life.dm
  aquila/code/modules/power/gravitygenerator.dm
  aquila/code/modules/shuttle/syndicate.dm
  aquila/code/modules/surgery/implant_removal.dm
  aquila/code/modules/uplink/uplink_devices.dm
  aquila/code/modules/uplink/uplink_items.dm
  aquila/icons/misc/infiltrator_pinpointer.dmi
  aquila/icons/obj/module.dmi
  aquila/sound/ambience/antag/infiltrator.ogg
  code/__DEFINES/role_preferences.dm
  code/__byond_version_compat.dm
  code/modules/clothing/chameleon.dm
  code/modules/mob/living/simple_animal/heretic_monsters.dm
  config/game_options.txt
Labels: Port, Feature, Nagroda

#295 Naprawia Summon Bats
  aquila/code/game/gamemodes/vampire/vampire_powers.dm
  aquila/code/modules/antagonists/vampire/vampire.dm
Labels: Bug Fix

#299 Naprawa błędu wizualnego emittera
  aquila/aquila.dm
  aquila/code/game/objects/effects/temporary_visuals/projectiles/impact.dm
  aquila/code/game/objects/effects/temporary_visuals/projectiles/muzzle.dm
  aquila/code/game/objects/effects/temporary_visuals/projectiles/tracer.dm
  code/modules/projectiles/projectile/beams.dm
Labels: Bug Fix

#267 Tonfa milicyjna
  aquila/aquila.dm
  aquila/code/game/objects/items/melee/misc.dm
  aquila/code/modules/surgery/bodyparts/bodyparts.dm
  aquila/code/modules/vending/security.dm
  aquila/icons/mob/inhands/equipment/security_lefthand.dmi
  aquila/icons/mob/inhands/equipment/security_righthand.dmi
  aquila/icons/obj/items_and_weapons.dmi
  code/game/objects/items/melee/misc.dm
  code/modules/jobs/job_types/head_of_security.dm
  code/modules/jobs/job_types/warden.dm
  nsv13/code/modules/jobs/job_types/marine/military_police.dm
Labels: Port, Feature

#254 Nie będziesz mi mówić jak żyć
  code/modules/cargo/packs.dm
Labels: Feature

#302 Małe błędziki z infilkami
  _maps/map_files/Atlantis/Atlantis2.dmm
  _maps/map_files/Serendipity/Serendipity2.dmm
  _maps/shuttles/infiltrator/infiltrator_cutter.dmm
  aquila/code/modules/shuttle/syndicate.dm
Labels: Bug Fix

#301 [Atlas] Losowe silniki - Rework Inżynierii, Atmosferyki, Kuchni, Baru, Botaniki, Jadalni, Biblioteki, Dormitoriów, Strefy rekreacyjnej
  _maps/RandomRooms/engine/atlas_engine_stormdrive.dmm
  _maps/RandomRooms/engine/atlas_engine_supermatter.dmm
  _maps/RandomRooms/engine/atlas_engine_tesla.dmm
  _maps/map_files/Atlas/atlas.dmm
  _maps/map_files/Atlas/atlas2.dmm
  aquila/aquila.dm
  aquila/code/game/objects/structures/stairs_dummy.dm
  code/game/objects/effects/spawners/roomspawner.dm
  code/modules/mapping/random_rooms.dm
  nsv13/code/modules/munitions/munitions_trolley.dm
Labels: Feature, Mapa

#305 tweaks
  aquila/code/_onclick/hud/alert.dm
  aquila/code/modules/events/infiltrators.dm
  aquila/code/modules/events/shit_storm.dm
  code/modules/jobs/job_types/ai.dm
  code/modules/jobs/job_types/assistant.dm
  code/modules/jobs/job_types/atmospheric_technician.dm
  code/modules/jobs/job_types/botanist.dm
  code/modules/jobs/job_types/brig_physician.dm
  code/modules/jobs/job_types/captain.dm
  code/modules/jobs/job_types/chemist.dm
  code/modules/jobs/job_types/chief_engineer.dm
  code/modules/jobs/job_types/chief_medical_officer.dm
  code/modules/jobs/job_types/cook.dm
  code/modules/jobs/job_types/cyborg.dm
  code/modules/jobs/job_types/deputy.dm
  code/modules/jobs/job_types/detective.dm
  code/modules/jobs/job_types/geneticist.dm
  code/modules/jobs/job_types/head_of_personnel.dm
  code/modules/jobs/job_types/head_of_security.dm
  code/modules/jobs/job_types/janitor.dm
  code/modules/jobs/job_types/lawyer.dm
  code/modules/jobs/job_types/medical_doctor.dm
  code/modules/jobs/job_types/paramedic.dm
  code/modules/jobs/job_types/quartermaster.dm
  code/modules/jobs/job_types/research_director.dm
  code/modules/jobs/job_types/roboticist.dm
  code/modules/jobs/job_types/scientist.dm
  code/modules/jobs/job_types/shaft_miner.dm
  code/modules/jobs/job_types/station_engineer.dm
  code/modules/jobs/job_types/virologist.dm
  code/modules/jobs/job_types/warden.dm
  config/jobs.txt
  config/maps.txt
  nsv13/code/modules/jobs/job_types/air_traffic_controller.dm
  nsv13/code/modules/jobs/job_types/bridge.dm
  nsv13/code/modules/jobs/job_types/marine/midshipman.dm
  nsv13/code/modules/jobs/job_types/marine/military_police.dm
  nsv13/code/modules/jobs/job_types/master_at_arms.dm
  nsv13/code/modules/jobs/job_types/munitions_technician.dm
  nsv13/code/modules/jobs/job_types/pilot.dm
Labels: Tweak, Config Update

#307 XDDDDDDD
  aquila/code/game/gamemodes/vampire/vampire_powers.dm
Labels: Bug Fix

#309 Quickfix mapping
  _maps/map_files/Atlas/atlas.dmm
  _maps/map_files/Atlas/atlas2.dmm
Labels: Bug Fix, mapping

#311 [snake] botanika
  _maps/map_files/Snake/snake_lower.dmm
Labels: Mapa, Joker nie lubi
