Repository aq33/NSV13, pull requests merged in 2024-01, with the labels that each got.

#23 kremufki, amarena, zoopa romana [port 193]
  aquila.dm
  aquila/code/modules/cargo/packs.dm
  aquila/code/modules/food_and_drinks/drinks/drinks.dm
  aquila/code/modules/food_and_drinks/food/snacks_pie.dm
  aquila/code/modules/food_and_drinks/recipes/drinks_recipes.dm
  aquila/code/modules/food_and_drinks/recipes/tablecraft/recipes_pie.dm
  aquila/code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  aquila/icons/obj/food/piecake.dmi
  code/modules/vending/boozeomat.dm
  icons/obj/drinks.dmi
Labels: sprites

#35 Overhaul dźwięków broni
  sound/weapons/gunshot.ogg
  sound/weapons/gunshot_silenced.ogg
  sound/weapons/laser.ogg
  sound/weapons/revolver357shot.ogg
  sound/weapons/revolver38shot.ogg
  sound/weapons/rifleshot.ogg
  sound/weapons/rocketlaunch.ogg
  sound/weapons/shotgunpump.ogg
  sound/weapons/shotgunshot.ogg
  sound/weapons/smgshot.ogg
  sound/weapons/taser2.ogg
Labels: sound

#33 poprawki na atlasie
  _maps/map_files/Atlas/atlas.dmm
  _maps/map_files/Atlas/atlas2.dmm
  _maps/map_files/Atlas/job_changes.dm
Labels: mapping

#38 Bluespace minery
  aquila.dm
  aquila/code/controllers/configuration/entries/game_options.dm
  aquila/code/game/objects/items/circuitboards/machine_circuitboards.dm
  aquila/code/game/objects/structures/crate_lockers/closets/secure/scientist.dm
  aquila/code/modules/mining/machine_bluespaceminer.dm
  aquila/code/modules/research/designs/machine_designs.dm
  aquila/code/modules/research/techweb/all_nodes.dm
  aquila/icons/obj/machines/mining_machines.dmi
  config/game_options.txt
Labels: Config Update

#37 Prawa ej aj
  aquila.dm
  aquila/code/datums/ai_laws.dm
  aquila/code/game/objects/items/AI_modules.dm
  aquila/code/modules/research/designs/AI_module_designs.dm
  code/datums/ai_laws.dm
  code/game/objects/effects/spawners/lootdrop.dm
  code/modules/research/techweb/all_nodes.dm
  config/game_options.txt
Labels: Config Update

#40 poprawia silnik na snake
  _maps/map_files/Snake/snake_lower.dmm
  _maps/map_files/Snake/snake_upper.dmm
Labels: mapping

#42 tłumaczenia część kolejna [PORT 1062]
  code/__DEFINES/jobs.dm
  code/__HELPERS/priority_announce.dm
  code/game/gamemodes/traitor/traitor.dm
  code/game/objects/effects/contraband.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/items/cards_ids.dm
  code/game/objects/items/storage/backpack.dm
  code/modules/antagonists/official/official.dm
  code/modules/client/preferences_toggles.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/modular_computers/computers/item/role_tablet_presets.dm
  icons/mob/screen_elite.dmi
  icons/mob/screen_gen.dmi
  icons/mob/screen_gen_old.dmi
  icons/mob/screen_midnight.dmi
  icons/mob/screen_operative.dmi
  icons/mob/screen_plasmafire.dmi
  icons/mob/screen_retro.dmi
Labels: sprites

#45 Mapa gulag
  _maps/map_files/Atlas/atlas.dmm
  _maps/map_files/Mining/nsv13/gulag.dmm
Labels: mapping

#49 poprawki mapowe do trawnika
  _maps/map_files/Serendipity/Serendipity1.dmm
  _maps/map_files/Serendipity/Serendipity2.dmm
Labels: mapping

#54 [atlas] Poprawki do poprawek oraz biblioteka
  _maps/map_files/Atlas/atlas.dmm
  _maps/map_files/Atlas/atlas2.dmm
  _maps/map_files/Atlas/job_changes.dm
  config/maps.txt
Labels: mapping, Config Update

#48 krwiste dźwięki
  aquila.dm
  aquila/code/game/objects/effects/decals/cleanable/humans.dm
  aquila/code/modules/mob/living/carbon/emote.dm
  aquila/code/modules/mob/living/carbon/human/emote.dm
  aquila/code/modules/mob/living/emote.dm
  aquila/sound/effects/bodybagpull.ogg
  aquila/sound/effects/bullet_hit.ogg
  aquila/sound/effects/closetpull.ogg
  aquila/sound/effects/crop_harvest.ogg
  aquila/sound/effects/dispenser.ogg
  aquila/sound/effects/fire.ogg
  aquila/sound/effects/lightswitch.ogg
  aquila/sound/effects/slice.ogg
  aquila/sound/effects/suture.ogg
  aquila/sound/machines/winerror.ogg
  aquila/sound/misc/bark.ogg
  aquila/sound/misc/dance.ogg
  aquila/sound/misc/meow.ogg
  aquila/sound/misc/purr.ogg
  aquila/sound/misc/wink.ogg
  aquila/sound/vehicles/jetpack.ogg
  aquila/sound/voice/burp.ogg
  aquila/sound/voice/groan.ogg
  aquila/sound/voice/human/cry.ogg
  aquila/sound/voice/human/vomit.ogg
  aquila/sound/voice/kiss.ogg
  aquila/sound/voice/sniff.ogg
  aquila/sound/voice/snore.ogg
  aquila/sound/voice/yawn.ogg
  aquila/sound/weapons/flamethrower.ogg
  code/controllers/subsystem/fire_burning.dm
  code/game/machinery/lightswitch.dm
  code/game/mecha/mecha.dm
  code/game/objects/items/flamethrower.dm
  code/game/objects/items/stacks/medical.dm
  code/game/objects/items/tanks/jetpack.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/crates_lockers/closets/bodybag.dm
  code/game/objects/structures/crates_lockers/closets/cardboardbox.dm
  code/modules/food_and_drinks/food/snacks.dm
  code/modules/food_and_drinks/kitchen_machinery/processor.dm
  code/modules/hydroponics/hydroponics.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/carbon_movement.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/silicon/robot/emote.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/simple_animal/friendly/cat.dm
  code/modules/mob/living/simple_animal/friendly/dog.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/projectile/bullets.dm
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
  icons/effects/blood.dmi
Labels: sprites

#55 mutation toxin + joker rozdaje metacoinsy
  aquila.dm
  aquila/code/modules/admin/verbs/modify_metacoins.dm
  aquila/code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/admin/admin.dm
  code/modules/admin/topic.dm
Labels: Administration

#53 tłumaczenia
  code/__DEFINES/radio.dm
  code/game/area/Space_Station_13_areas.dm
  code/game/area/ai_monitored.dm
  code/game/atoms_movable.dm
  code/game/gamemodes/events.dm
  code/game/gamemodes/objective.dm
  nsv13/code/game/area/aetherwhisp.dm
  nsv13/code/game/area/areas.dm
  nsv13/code/game/area/boarding_areas.dm
  nsv13/code/game/area/hammerhead.dm
  nsv13/code/game/area/hammurabi.dm
  nsv13/code/game/area/pegasus.dm
  strings/dreamstrings.txt
  strings/greek_letters.txt
  strings/numbers_as_words.txt
  strings/phobia.json
  strings/wanted_message.json
Labels: Tłumaczenie

#58 tłumaczy bełkot naukowców + imiona
  aquila.dm
  aquila/code/__HELPERS/names.dm
  code/__HELPERS/mobs.dm
  code/__HELPERS/names.dm
  code/_globalvars/lists/names.dm
  code/datums/diseases/advance/advance.dm
  code/game/machinery/computer/security.dm
  code/game/objects/items/cardboard_cutouts.dm
  code/game/objects/items/cards_ids.dm
  code/modules/antagonists/_common/antag_spawner.dm
  code/modules/antagonists/ert/ert.dm
  code/modules/antagonists/nukeop/nukeop.dm
  code/modules/client/preferences2/character_save.dm
  code/modules/language/language.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/golems.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/ghost.dm
  strings/names/first_female.txt
  strings/names/first_male.txt
  strings/names/last_female.txt
  strings/names/last_male.txt
Labels: Feature, Tłumaczenie

#59 reszta tłumaczeń i idk co jeszcze
  aquila/code/__DEFINES/DNA.dm
  code/controllers/subsystem/nightshift.dm
  code/datums/weather/weather_types/ash_storm.dm
  code/game/objects/obj_defense.dm
  code/game/turfs/closed/walls.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/simple_animal/bot/bot.dm
  code/modules/projectiles/projectile/energy/stun.dm
  code/modules/projectiles/projectile/special/hallucination.dm
  code/modules/surgery/organs/tongue.dm
  html/antagtips/nukie.html
  html/antagtips/traitor.html
  html/antagtips/wizard.html
  html/antagtips/xeno.html
Labels: Tłumaczenie

#62 Zmienia lokalizacje aquila.dm, sortuje aquila.dm i dodaje brakujące ścieżki
  aquila.dm
  aquila/aquila.dm
  aquila/code/modules/mob/living/simple_animal/hostile/mining_mobs/hivelord.dm
  nsv13.dme
Labels: Tweak

#63 [atlas] medbay zmiany + fixy w innych miejscach
  _maps/map_files/Atlas/atlas.dmm
  _maps/map_files/Atlas/atlas2.dmm
  _maps/map_files/Atlas/job_changes.dm
Labels: mapping

#64 Kosmobagiety [Port 428]
  icons/mob/back.dmi
  icons/mob/belt.dmi
  icons/mob/clothing/back.dmi
  icons/mob/clothing/belt.dmi
  icons/mob/clothing/head.dmi
  icons/mob/clothing/suit.dmi
  icons/mob/clothing/uniform.dmi
  icons/mob/ears.dmi
  icons/mob/eyes.dmi
  icons/mob/head.dmi
  icons/mob/inhands/equipment/backpack_lefthand.dmi
  icons/mob/inhands/equipment/backpack_righthand.dmi
  icons/mob/suit.dmi
  icons/mob/uniform.dmi
  icons/obj/card.dmi
  icons/obj/closet.dmi
  icons/obj/clothing/belts.dmi
  icons/obj/clothing/glasses.dmi
  icons/obj/clothing/gloves.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/uniforms.dmi
  icons/obj/doors/airlocks/station/security.dmi
  icons/obj/storage.dmi
  icons/obj/vending.dmi
  nsv13/icons/obj/card.dmi
Labels: sprites

#68 Aktualizacja do NSV13
  code/__DEFINES/tgs.dm
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/recycling/conveyor.dm
  code/modules/tgs/core/core.dm
  code/modules/tgs/v5/__interop_version.dm
  code/modules/tgs/v5/_defines.dm
  code/modules/tgs/v5/api.dm
  code/modules/tgs/v5/bridge.dm
  code/modules/tgs/v5/topic.dm
  code/modules/tgs/v5/undefs.dm
  html/changelog.html
  html/changelogs/.all_changelog.yml
  nsv13.dme
  nsv13/code/controllers/subsystem/map_vote.dm
  nsv13/code/controllers/subsystem/overmap_mode.dm
  nsv13/code/controllers/subsystem/starsystem.dm
  nsv13/code/datums/starsystem_manager.dm
  nsv13/code/game/gamemodes/overmap/objectives/rubicon.dm
  nsv13/code/modules/mob/living/carbon/carbon.dm
  nsv13/code/modules/mob/living/carbon/human/human.dm
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/revision2/automation.dm
  nsv13/code/modules/overmap/FTL/components/drive.dm
  nsv13/code/modules/overmap/ai-skynet.dm
  nsv13/code/modules/overmap/factions.dm
  nsv13/code/modules/overmap/overmap.dm
  nsv13/code/modules/overmap/verbs.dm
  tgui/packages/tgui/interfaces/StarsystemManager.js
  tgui/yarn.lock
Labels: TGUI-Changes

#69 Cargo skrzynki
  code/modules/cargo/packs.dm
  code/modules/mining/machine_vending.dm
Labels: Tweak

#66 Cele załogi - tłumaczenie [Port 540]
  code/modules/crew_objectives/_crew_objectives.dm
  code/modules/crew_objectives/cargo_objectives.dm
  code/modules/crew_objectives/civilian_objectives.dm
  code/modules/crew_objectives/command_objectives.dm
  code/modules/crew_objectives/engineering_objectives.dm
  code/modules/crew_objectives/medical_objectives.dm
  code/modules/crew_objectives/science_objectives.dm
  code/modules/crew_objectives/security_objectives.dm
Labels: Tłumaczenie

#70 poprawki mapowe atlas + trawnik czesc 4
  _maps/map_files/Atlas/atlas.dmm
  _maps/map_files/Atlas/atlas2.dmm
  _maps/map_files/Serendipity/Serendipity1.dmm
  _maps/shuttles/emergency/emergency_atlas.dmm
Labels: Mapa, mapping

#39 Dodaje atlantis, DO MERGE
  _maps/atlantis.dm
  _maps/atlantis.json
  _maps/map_files/Atlantis/Atlantis.dmm
  _maps/map_files/Atlantis/Atlantis2.dmm
  _maps/map_files/Atlantis/job_changes.dm
  config/maps.txt
Labels: Mapa, mapping, Config Update

#76 Ładowanie mapy gułagu
  _maps/atlas.json
  aquila/aquila.dm
  aquila/code/modules/shuttle/super_cruise/orbital_map_components/orbital_objects/beacon.dm
  code/controllers/subsystem/mapping.dm
  code/datums/map_config.dm
Labels: Mapa, mapping
